"use client";
import Link from "next/link";
import ProductCard from "../components/ProductCard";
import {useEffect,useState} from "react";
const products=[
{id:"1",title:"Vintage Camera Collection",category:"Collectibles",bid:420,min:250,bids:18,seller:"North Archive",image:"https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80"},
{id:"2",title:"Art Deco Desk Clock",category:"Antiques",bid:185,min:120,bids:9,seller:"Old & Found",image:"https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&w=900&q=80"},
{id:"3",title:"Retro Vinyl Set",category:"Music",bid:96,min:60,bids:14,seller:"Groove Vault",image:"https://images.unsplash.com/photo-1461360228754-6e81c478b882?auto=format&fit=crop&w=900&q=80"},
{id:"4",title:"Signed Collector Poster",category:"Memorabilia",bid:310,min:200,bids:12,seller:"Paper Moon",image:"https://images.unsplash.com/photo-1561214115-89c43c1d9b89?auto=format&fit=crop&w=900&q=80"}];
export default function Home(){const[ready,setReady]=useState(false);useEffect(()=>{const t=setTimeout(()=>setReady(true),1900);return()=>clearTimeout(t)},[]);if(!ready)return <main className="welcome-screen"><div className="welcome-triangle"><i/><i/><i/></div><div className="welcome-brand">B<span>ID</span></div><div className="welcome-loading">LOADING MARKETPLACE</div></main>;return <main className="page"><section className="hero glass"><div className="eyebrow">BID MARKETPLACE · PRIVATE BY DESIGN</div><h1>Find something rare.<br/><span>Make your bid.</span></h1><p>Discover collectibles, antiques, memorabilia and other listed items. Sellers set the minimum; interested buyers compete through bids.</p><div className="hero-actions"><Link className="btn primary" href="/explore">Explore listings</Link><Link className="btn ghost" href="/sell">List an item</Link></div><div className="stats"><div><b>Live</b><small>auction-style listings</small></div><div><b>Private</b><small>contact stays hidden</small></div><div><b>18+</b><small>restricted categories gated</small></div></div></section><section className="section-head"><div><span className="eyebrow">TRENDING NOW</span><h2>Open bids</h2></div><Link href="/explore" className="text-link">View all →</Link></section><section className="product-grid">{products.map(p=><ProductCard key={p.id} product={p}/>)}</section></main>}
