"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {getClientAuth,setClientAuth} from "../../lib/auth";
export default function Sell(){const r=useRouter();const[auth,setAuth]=useState(null);const[sent,setSent]=useState(false);const[convert,setConvert]=useState(false);const cats=["Antiques","Collectibles","Vintage","Art","Memorabilia","Music","Books","Fashion","Other","18+ Restricted"];
useEffect(()=>{setAuth(getClientAuth())},[]);
if(!auth)return <main className="auth-gate page"><section className="glass auth-card center"><span className="eyebrow">SELLER ACCESS</span><h1>Seller login required</h1><p className="small-copy">You need an authenticated seller account before publishing an item.</p><button className="btn primary wide" onClick={()=>r.push("/login?next=/sell&role=seller")}>Login as seller</button><button className="btn ghost wide" onClick={()=>r.push("/signup?role=seller&next=/sell")}>Create seller account</button></section></main>;
if(auth.role!=="seller")return <main className="auth-gate page"><section className="glass auth-card center"><span className="eyebrow">SELLER ACCESS</span><h1>Convert to seller account</h1><p className="small-copy">You are signed in as a buyer. Convert this account before creating listings.</p><button className="btn primary wide" onClick={()=>{const x={...auth,role:"seller"};setClientAuth(x);setAuth(x)}}>Convert to seller account</button></section></main>;
return <main className="page"><section className="page-title glass"><span className="eyebrow">SELLER DESK</span><h1>Publish a listing</h1><p>Set a minimum bid, describe the item accurately and choose the correct category.</p></section><form className="listing-form glass" onSubmit={e=>{e.preventDefault();setSent(true)}}><label>Item title<input required placeholder="e.g. Vintage desk clock"/></label><label>Category<select required><option value="">Choose category</option>{cats.map(c=><option key={c}>{c}</option>)}</select></label><div className="two"><label>Minimum bid<input required type="number" min="0" placeholder="250"/></label><label>Currency<select><option>USD $</option><option>GBP £</option><option>INR ₹</option></select></label></div><label>Image URL<input type="url" placeholder="https://..."/></label><label>Description<textarea required rows="6" placeholder="Condition, history, included items, shipping information..."/></label><label>Discount / offer<input placeholder="Optional"/></label><label className="check"><input type="checkbox" required/> I confirm the listing follows applicable laws, platform rules and category restrictions.</label><button className="btn primary">{sent?"Listing saved in demo mode":"Publish listing"}</button>{sent&&<div className="notice">Demo listing created locally. Connect a database and moderation service before public transactions.</div>}</form></main>}
