"use client";
import {useEffect,useState} from "react";import Link from "next/link";import {useRouter,useSearchParams} from "next/navigation";import {setClientAuth,strongPassword} from "../../lib/auth";import {signIn} from "next-auth/react";
function Triangle(){return <div className="triangle-visual" aria-hidden="true"><div className="tri tri-a">△</div><div className="tri tri-b">△</div></div>}
export default function Login(){const router=useRouter(),sp=useSearchParams(),[role,setRole]=useState(sp.get("role")||"buyer"),[email,setEmail]=useState(""),[pass,setPass]=useState(""),[error,setError]=useState("");const next=sp.get("next")||"/";
useEffect(()=>{if(sp.get("role"))setRole(sp.get("role"))},[sp]);const submit=e=>{e.preventDefault();if(!email||pass.length<8){setError("Enter a valid email and a password of at least 8 characters.");return}setClientAuth({name:email.split("@")[0],email,role,provider:"password",authenticatedAt:Date.now()});router.push(next)};const oauth=(provider)=>{
  if(provider==="Google"){
    signIn("google",{callbackUrl:next});
  }else{
    setError("Apple login will be connected after Apple OAuth credentials are configured.");
  }
};return <main className="auth-page"><Triangle/><section className="auth-card glass"><span className="eyebrow">WELCOME BACK</span><h1>Sign in to BID</h1><div className="role-switch">{["buyer","seller"].map(x=><button key={x} className={role===x?"active":""} onClick={()=>setRole(x)}>{x}</button>)}</div><form onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required placeholder="you@example.com"/></label><label>Password<input value={pass} onChange={e=>setPass(e.target.value)} type="password" required minLength={8} placeholder="At least 8 characters"/></label><button className="btn primary wide">Sign in as {role}</button></form>{error&&<div className="notice">{error}</div>}<div className="auth-divider"><span>or continue securely with</span></div><div className="auth-social"><button type="button" className="social-btn google" onClick={()=>oauth("Google")}>G&nbsp;&nbsp; Google</button><button type="button" className="social-btn apple" onClick={()=>oauth("Apple")}>●&nbsp;&nbsp; Apple</button></div><p className="center small-copy">New here? <Link href={`/signup?role=${role}&next=${encodeURIComponent(next)}`} className="text-link">Create account</Link></p></section></main>}
